language: c

sudo: false

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; sudo apt-get install valgrind; fi

script: 
    - ./configure
    - cd build && make && make test ARGS=--output-on-failure
